/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentavehiculo.Datos;

/**
 *
 * @author estiv
 */
public class ALQUILER extends javax.swing.JFrame {

    /**
     * Creates new form ALQUILER
     */
    public ALQUILER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLaalquilervehiculo = new javax.swing.JLabel();
        jLaedad = new javax.swing.JLabel();
        jTexedad = new javax.swing.JTextField();
        jLapase = new javax.swing.JLabel();
        jTexcategoria = new javax.swing.JTextField();
        jLatarcredito = new javax.swing.JLabel();
        jTexpase = new javax.swing.JTextField();
        jLadircontacto = new javax.swing.JLabel();
        jLacategoria = new javax.swing.JLabel();
        jTexdircontacto = new javax.swing.JTextField();
        jTexcedula = new javax.swing.JTextField();
        jLacedula = new javax.swing.JLabel();
        jTextelefono = new javax.swing.JTextField();
        jLanombre = new javax.swing.JLabel();
        jTextarcredito = new javax.swing.JTextField();
        jLaapellido = new javax.swing.JLabel();
        jTexnombre = new javax.swing.JTextField();
        jLatelefono = new javax.swing.JLabel();
        jTexapellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jBuguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLaalquilervehiculo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLaalquilervehiculo.setText("ALQUILER VEHICULO");

        jLaedad.setText("EDAD");

        jTexedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexedadActionPerformed(evt);
            }
        });

        jLapase.setText("PASE");

        jTexcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcategoriaActionPerformed(evt);
            }
        });

        jLatarcredito.setText("TAR. CREDITO");

        jTexpase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexpaseActionPerformed(evt);
            }
        });

        jLadircontacto.setText("DIR CONTACTO");

        jLacategoria.setText("CATEGORIA");

        jTexdircontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexdircontactoActionPerformed(evt);
            }
        });

        jTexcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcedulaActionPerformed(evt);
            }
        });

        jLacedula.setText("CEDULA");

        jTextelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextelefonoActionPerformed(evt);
            }
        });

        jLanombre.setText("NOMBRE");

        jTextarcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextarcreditoActionPerformed(evt);
            }
        });

        jLaapellido.setText("APELLIDO");

        jTexnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexnombreActionPerformed(evt);
            }
        });

        jLatelefono.setText("TELEFONO");

        jTexapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexapellidoActionPerformed(evt);
            }
        });

        jLabel1.setText("falta poner nombre de variables");

        jBuguardar.setText("GUARDAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLaalquilervehiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jBuguardar)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLanombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTexnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLacedula)
                                .addComponent(jLatelefono)
                                .addComponent(jLadircontacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLatarcredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTexdircontacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTexcedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextarcredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLacategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLaapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLaedad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLapase, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTexcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexpase, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexedad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLaalquilervehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addComponent(jBuguardar)
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLanombre)
                        .addComponent(jLaapellido)
                        .addComponent(jTexnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(19, 19, 19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLacedula)
                        .addComponent(jLaedad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexedad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLatelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLapase, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexpase, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLadircontacto)
                        .addComponent(jLacategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexdircontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTexcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLatarcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextarcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(110, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexedadActionPerformed

    private void jTexcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexcategoriaActionPerformed

    private void jTexpaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexpaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexpaseActionPerformed

    private void jTexdircontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexdircontactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexdircontactoActionPerformed

    private void jTexcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexcedulaActionPerformed

    private void jTextelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextelefonoActionPerformed

    private void jTextarcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextarcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextarcreditoActionPerformed

    private void jTexnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexnombreActionPerformed

    private void jTexapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexapellidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ALQUILER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ALQUILER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ALQUILER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ALQUILER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ALQUILER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuguardar;
    private javax.swing.JLabel jLaalquilervehiculo;
    private javax.swing.JLabel jLaapellido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLacategoria;
    private javax.swing.JLabel jLacedula;
    private javax.swing.JLabel jLadircontacto;
    private javax.swing.JLabel jLaedad;
    private javax.swing.JLabel jLanombre;
    private javax.swing.JLabel jLapase;
    private javax.swing.JLabel jLatarcredito;
    private javax.swing.JLabel jLatelefono;
    private javax.swing.JTextField jTexapellido;
    private javax.swing.JTextField jTexcategoria;
    private javax.swing.JTextField jTexcedula;
    private javax.swing.JTextField jTexdircontacto;
    private javax.swing.JTextField jTexedad;
    private javax.swing.JTextField jTexnombre;
    private javax.swing.JTextField jTexpase;
    private javax.swing.JTextField jTextarcredito;
    private javax.swing.JTextField jTextelefono;
    // End of variables declaration//GEN-END:variables
}
