/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentavehiculo.Datos;

/**
 *
 * @author estiv
 */
public class JFCLIENTES extends javax.swing.JFrame {

    /**
     * Creates new form JFCLIENTES
     */
    public JFCLIENTES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLadatosclientes = new javax.swing.JLabel();
        jLacedula = new javax.swing.JLabel();
        jLanombre = new javax.swing.JLabel();
        jLaapellido = new javax.swing.JLabel();
        jLatelefono = new javax.swing.JLabel();
        jLaedad = new javax.swing.JLabel();
        jLapase = new javax.swing.JLabel();
        jLatarcredito = new javax.swing.JLabel();
        jLadircontacto = new javax.swing.JLabel();
        jLacategoria = new javax.swing.JLabel();
        jTexdircontacto = new javax.swing.JTextField();
        jTexcedula = new javax.swing.JTextField();
        jTextelefono = new javax.swing.JTextField();
        jTextarcredito = new javax.swing.JTextField();
        jTexnombre = new javax.swing.JTextField();
        jTexapellido = new javax.swing.JTextField();
        jTexedad = new javax.swing.JTextField();
        jTexcategoria = new javax.swing.JTextField();
        jTexpase = new javax.swing.JTextField();
        jBuguardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLadatosclientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLadatosclientes.setText("DATOS CLIENTES");

        jLacedula.setText("CEDULA");

        jLanombre.setText("NOMBRE");

        jLaapellido.setText("APELLIDO");

        jLatelefono.setText("TELEFONO");

        jLaedad.setText("EDAD");

        jLapase.setText("PASE");

        jLatarcredito.setText("TAR. CREDITO");

        jLadircontacto.setText("DIR CONTACTO");

        jLacategoria.setText("CATEGORIA");

        jTexdircontacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexdircontactoActionPerformed(evt);
            }
        });

        jTexcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcedulaActionPerformed(evt);
            }
        });

        jTextelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextelefonoActionPerformed(evt);
            }
        });

        jTextarcredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextarcreditoActionPerformed(evt);
            }
        });

        jTexnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexnombreActionPerformed(evt);
            }
        });

        jTexapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexapellidoActionPerformed(evt);
            }
        });

        jTexedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexedadActionPerformed(evt);
            }
        });

        jTexcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcategoriaActionPerformed(evt);
            }
        });

        jTexpase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexpaseActionPerformed(evt);
            }
        });

        jBuguardar.setText("GUARDAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLadatosclientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLanombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTexnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLacedula)
                                    .addComponent(jLatelefono)
                                    .addComponent(jLadircontacto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLatarcredito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTexdircontacto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTexcedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextarcredito, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLacategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLaapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLaedad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLapase, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTexcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexpase, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexedad, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jBuguardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLadatosclientes)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLanombre)
                    .addComponent(jLaapellido)
                    .addComponent(jTexnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLacedula)
                    .addComponent(jLaedad, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexedad, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLatelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLapase, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexpase, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLadircontacto)
                    .addComponent(jLacategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexdircontacto, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLatarcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextarcredito, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jBuguardar)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTexdircontactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexdircontactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexdircontactoActionPerformed

    private void jTexcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexcedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexcedulaActionPerformed

    private void jTextelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextelefonoActionPerformed

    private void jTextarcreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextarcreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextarcreditoActionPerformed

    private void jTexnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexnombreActionPerformed
           // TODO add your handling code here:
    }//GEN-LAST:event_jTexnombreActionPerformed

    private void jTexapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexapellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexapellidoActionPerformed

    private void jTexedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexedadActionPerformed

    private void jTexcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexcategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexcategoriaActionPerformed

    private void jTexpaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexpaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexpaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCLIENTES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCLIENTES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuguardar;
    private javax.swing.JLabel jLaapellido;
    private javax.swing.JLabel jLacategoria;
    private javax.swing.JLabel jLacedula;
    private javax.swing.JLabel jLadatosclientes;
    private javax.swing.JLabel jLadircontacto;
    private javax.swing.JLabel jLaedad;
    private javax.swing.JLabel jLanombre;
    private javax.swing.JLabel jLapase;
    private javax.swing.JLabel jLatarcredito;
    private javax.swing.JLabel jLatelefono;
    private javax.swing.JTextField jTexapellido;
    private javax.swing.JTextField jTexcategoria;
    private javax.swing.JTextField jTexcedula;
    private javax.swing.JTextField jTexdircontacto;
    private javax.swing.JTextField jTexedad;
    private javax.swing.JTextField jTexnombre;
    private javax.swing.JTextField jTexpase;
    private javax.swing.JTextField jTextarcredito;
    private javax.swing.JTextField jTextelefono;
    // End of variables declaration//GEN-END:variables
}
